web:
    container_name: ${SERVER_NAME}
    build: .docker/
    volumes:
        - ./:/var/www/html
#        - $SSH_AUTH_SOCK:/tmp/agent.sock
    env_file:
        - .env
    environment:
        DOMAIN_NAME: ${SERVER_NAME}.dev
        SSH_AUTH_SOCK: /tmp/agent.sock
    ports:
        - 80:80
        - 8000:8000
    links:
        - db
db:
    container_name: ${SERVER_NAME}_db
    image: mysql:5
    user: ${DOCKER_UID}
    environment:
        DOMAIN_NAME: ${SERVER_NAME}-db.dev
        MYSQL_DATABASE: ${DB_DATABASE}
        MYSQL_USER: ${DB_USERNAME}
        MYSQL_PASSWORD: ${DB_PASSWORD}
        MYSQL_ROOT_PASSWORD: root
        MYSQL_ALLOW_EMPTY_PASSWORD: 1
    volumes:
        - ./.docker/data:/var/lib/mysql
        - ./:/var/www/html
        - ./.docker:/etc/mysql/conf.d
    ports:
        - ${DB_PORT}:${DB_PORT}
mail:
    container_name: ${SERVER_NAME}_mail
    image: helder/mailcatcher
    environment:
        DOMAIN_NAME: ${SERVER_NAME}-mail.dev

